export const PAGINATION__LOAD_SUCCESS = '[PAGINATION/API] Load PAGINATION Success';
export const PAGINATION__LOAD_WITH_FILTERS = '[PAGINATION/API] Load PAGINATION with filters';
export const PAGINATION__LOAD_WITH_LOAD_PAGE = '[PAGINATION/API] Load PAGINATION with load page';
export const PAGINATION__LOAD_FAILURE = '[PAGINATION/API] Load PAGINATION failure';
