export const NAV__MODAL_OPEN = '[NAV] Open modal';
export const NAV__MODAL_CLOSE = '[NAV] Close modal';
export const NAV__SET_SELECTED_LINK = '[NAV] Set selected link';
export const NAV__TOGGLE_MODAL = '[NAV] Toggle modal';
export const NAV__UI_SET_DATA = '[NAV] Ui set data';
export const NAV__MOBILE_DROP_DOWN_MENU_SET_DATA = '[NAV] Set data for mobile drop down menu';
export const NAV__TOGGLE_MOBILE_DROP_DOWN_MENU = '[NAV] Toggle mobile drop down menu';
export const NAV__CLOSE_MOBILE_DROP_DOWN_MENU = '[NAV] Close mobile drop down menu';
export const NAV__CLICK_CATEGORY = '[NAV] Click Category';
