export const FILTERS__LOAD_SUCCESS = '[FILTERS/API] Load filters Success';
export const FILTERS__LOAD = '[FILTERS/API] Load filters';
export const FILTERS__LOAD_FAILURE = '[FILTERS/API] Load filters failure';
export const FILTERS__ADD_CURRENT_FILTER = '[FILTERS/API] Add current filter';
export const FILTERS__REMOVE_CURRENT_FILTER = '[FILTERS/API] Remove current filter';
export const FILTERS__TOGGLE_CURRENT_FILTER = '[FILTERS/API] TOGGLE current filter';
export const FILTERS__CLEAR_ALL_CURRENT_FILTERS = '[FILTERS/API] Clear all current filters';
export const FILTERS__UPDATE_COUNTS = '[FILTERS] Update counts';
export const FILTERS__UPDATE_COUNTS_SUCCESS = '[FILTERS] Update counts success';
export const FILTERS__ADD_ROUTE_CURRENT_FILTERS = '[FILTERS/API] Add route current filters';
export const FILTERS__TOGGLE_SHOW_UNAVAIASBLE_WINES = '[FILTERS/API] TOGGLE ShowUnavailableWines';
export const FILTERS__SET_PRICE_RANGE_VALUES = '[FILTERS/API] SET PriceRangeValues';
export const FILTERS__CLEAR_PRICE_RANGE_VALUES = '[FILTERS/API] CLEAR PriceRangeValues';
export const FILTERS__SET_RATING_RANGE_VALUES = '[FILTERS/API] SET RatingRangeValues';
export const FILTERS__CLEAR_RATING_RANGE_VALUES = '[FILTERS/API] CLEAR RatingRangeValues';
export const FILTERS__TOGGLE_FILTER_PANEL_OPEN = '[FILTERS] Toggle Filter Panel Open';

export const SET_WINE_LIST_SORT_VALUE = '[SORT/API] Set Wine List Sort Value';
export const CLEAR_WINE_LIST_SORT_VALUE = '[SORT/API] Clear Wine List Sort Value';
